#!/bin/sh
set -e -u

# Settings
#

# Options processing.
#

# Inlined definitions of main, defaults, &c.
#

go() {
  cd_p "$work_dir"
  archives
  //wrappers// \
  env //env// \
  sh -c 'exec "$@"' sh ... "$@"
}

archives() {
  cd_p "$work_dir"
  # { ...put SHDAT tarball here... } | tar x
  # { ...put SHDAT tarball here... } | tar xz
  # { ...put SHDAT tarball here... } | tar xj
  # { ...put SHDAT tarball here... } | tar xz
  # { ...put SHDAT tarball here... } | tar x
}
go "$@" # Args are simply passed to the user's program.
exit
