#!/bin/bash
set -o errexit -o pipefail -o nounset

function comments {
  sed 's/ *# *.*$//'
}

function whitespace {
  sed 's/ *$// ; /^$/ d'
}

function only_decls {
  sed -n '/^: \${/ p
          /^[a-zA-Z_][a-zA-Z_0-9]*() {$/,/^}$/ p'
}

"${1:-cat}" |
"${2:-cat}" |
"${3:-cat}" |
"${4:-cat}" |
"${5:-cat}" |
"${6:-cat}" |
"${7:-cat}" |
"${8:-cat}" |
"${9:-cat}"

