#!/bin/sh
set -e -u
# ARX requires that at least these shell functions are available in the shell
# libary. They are prepended to every shell library (and thus can be
# overridden).

source_() {
  [ ! -s "$1" ] || . "$1"
  shift
  "$@"
}

exec_() {
  exec "$@"
}

trap_dot() {

}

